services:
  talkvn.webapi:
    image: ${DOCKER_REGISTRY-}talkvnwebapi
    build:
      context: ../../
      dockerfile: src/TalkVN.WebAPI/Dockerfile
    ports:
      - "8084:8080"
      - "8085:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/talkvn.pfx
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=talkvn
    env_file:
      - ../../src/TalkVN.WebAPI/.env
    networks:
      - productnetwork
    restart: unless-stopped
    
  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: "Password12345!"
      MYSQL_DATABASE: talkvndb
    ports:
      - "3306:3306"
    volumes:
      - mysqlvol:/var/lib/mysql
    networks:
      - productnetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  productnetwork:
    
volumes:
  mysqlvol:
